//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free_SysLog.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string logFileLocation {
            get {
                return ((string)(this["logFileLocation"]));
            }
            set {
                this["logFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("816, 173")]
        public global::System.Drawing.Size logViewerWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["logViewerWindowSize"]));
            }
            set {
                this["logViewerWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoScroll {
            get {
                return ((bool)(this["autoScroll"]));
            }
            set {
                this["autoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1191, 485")]
        public global::System.Drawing.Size mainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["mainWindowSize"]));
            }
            set {
                this["mainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196")]
        public int columnTimeSize {
            get {
                return ((int)(this["columnTimeSize"]));
            }
            set {
                this["columnTimeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int columnIPSize {
            get {
                return ((int)(this["columnIPSize"]));
            }
            set {
                this["columnIPSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("670")]
        public int columnLogSize {
            get {
                return ((int)(this["columnLogSize"]));
            }
            set {
                this["columnLogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoSave {
            get {
                return ((bool)(this["autoSave"]));
            }
            set {
                this["autoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public short autoSaveMinutes {
            get {
                return ((short)(this["autoSaveMinutes"]));
            }
            set {
                this["autoSaveMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("514")]
        public int sysLogPort {
            get {
                return ((int)(this["sysLogPort"]));
            }
            set {
                this["sysLogPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ignored {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ignored"]));
            }
            set {
                this["ignored"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color searchColor {
            get {
                return ((global::System.Drawing.Color)(this["searchColor"]));
            }
            set {
                this["searchColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1168, 464")]
        public global::System.Drawing.Size ignoredWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ignoredWindowSize"]));
            }
            set {
                this["ignoredWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point windowLocation {
            get {
                return ((global::System.Drawing.Point)(this["windowLocation"]));
            }
            set {
                this["windowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ignoredWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["ignoredWindowLocation"]));
            }
            set {
                this["ignoredWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ignoredWordsLocation {
            get {
                return ((global::System.Drawing.Point)(this["ignoredWordsLocation"]));
            }
            set {
                this["ignoredWordsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool recordIgnoredLogs {
            get {
                return ((bool)(this["recordIgnoredLogs"]));
            }
            set {
                this["recordIgnoredLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection replacements {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["replacements"]));
            }
            set {
                this["replacements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolMaximized {
            get {
                return ((bool)(this["boolMaximized"]));
            }
            set {
                this["boolMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolConfirmClose {
            get {
                return ((bool)(this["boolConfirmClose"]));
            }
            set {
                this["boolConfirmClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ignored2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ignored2"]));
            }
            set {
                this["ignored2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point replacementsLocation {
            get {
                return ((global::System.Drawing.Point)(this["replacementsLocation"]));
            }
            set {
                this["replacementsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point searchWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["searchWindowLocation"]));
            }
            set {
                this["searchWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1168, 464")]
        public global::System.Drawing.Size searchWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["searchWindowSize"]));
            }
            set {
                this["searchWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection alerts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["alerts"]));
            }
            set {
                this["alerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point alertsLocation {
            get {
                return ((global::System.Drawing.Point)(this["alertsLocation"]));
            }
            set {
                this["alertsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolDeselectItemsWhenMinimizing {
            get {
                return ((bool)(this["boolDeselectItemsWhenMinimizing"]));
            }
            set {
                this["boolDeselectItemsWhenMinimizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolShowAlertedColumn {
            get {
                return ((bool)(this["boolShowAlertedColumn"]));
            }
            set {
                this["boolShowAlertedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("345")]
        public int colIgnoredReplace {
            get {
                return ((int)(this["colIgnoredReplace"]));
            }
            set {
                this["colIgnoredReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colIgnoredRegex {
            get {
                return ((int)(this["colIgnoredRegex"]));
            }
            set {
                this["colIgnoredRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("91")]
        public int colIgnoredCaseSensitive {
            get {
                return ((int)(this["colIgnoredCaseSensitive"]));
            }
            set {
                this["colIgnoredCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colIgnoredEnabled {
            get {
                return ((int)(this["colIgnoredEnabled"]));
            }
            set {
                this["colIgnoredEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("345")]
        public int colReplacementsReplace {
            get {
                return ((int)(this["colReplacementsReplace"]));
            }
            set {
                this["colReplacementsReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("345")]
        public int colReplacementsReplaceWith {
            get {
                return ((int)(this["colReplacementsReplaceWith"]));
            }
            set {
                this["colReplacementsReplaceWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colReplacementsRegex {
            get {
                return ((int)(this["colReplacementsRegex"]));
            }
            set {
                this["colReplacementsRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("91")]
        public int colReplacementsCaseSensitive {
            get {
                return ((int)(this["colReplacementsCaseSensitive"]));
            }
            set {
                this["colReplacementsCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colReplacementsEnabled {
            get {
                return ((int)(this["colReplacementsEnabled"]));
            }
            set {
                this["colReplacementsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308")]
        public int colAlertsAlertLogText {
            get {
                return ((int)(this["colAlertsAlertLogText"]));
            }
            set {
                this["colAlertsAlertLogText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("257")]
        public int colAlertsAlertText {
            get {
                return ((int)(this["colAlertsAlertText"]));
            }
            set {
                this["colAlertsAlertText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colAlertsRegex {
            get {
                return ((int)(this["colAlertsRegex"]));
            }
            set {
                this["colAlertsRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("91")]
        public int colAlertsCaseSensitive {
            get {
                return ((int)(this["colAlertsCaseSensitive"]));
            }
            set {
                this["colAlertsCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int colAlertsType {
            get {
                return ((int)(this["colAlertsType"]));
            }
            set {
                this["colAlertsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int colAlertsEnabled {
            get {
                return ((int)(this["colAlertsEnabled"]));
            }
            set {
                this["colAlertsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("670, 304")]
        public global::System.Drawing.Size ConfigureIgnoredSize {
            get {
                return ((global::System.Drawing.Size)(this["ConfigureIgnoredSize"]));
            }
            set {
                this["ConfigureIgnoredSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1051, 489")]
        public global::System.Drawing.Size ConfigureReplacementsSize {
            get {
                return ((global::System.Drawing.Size)(this["ConfigureReplacementsSize"]));
            }
            set {
                this["ConfigureReplacementsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1003, 322")]
        public global::System.Drawing.Size ConfigureAlertsSize {
            get {
                return ((global::System.Drawing.Size)(this["ConfigureAlertsSize"]));
            }
            set {
                this["ConfigureAlertsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ServersToSendTo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServersToSendTo"]));
            }
            set {
                this["ServersToSendTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeToClockTray {
            get {
                return ((bool)(this["MinimizeToClockTray"]));
            }
            set {
                this["MinimizeToClockTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteOldLogsAtMidnight {
            get {
                return ((bool)(this["DeleteOldLogsAtMidnight"]));
            }
            set {
                this["DeleteOldLogsAtMidnight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1168, 464")]
        public global::System.Drawing.Size logFileViewerSize {
            get {
                return ((global::System.Drawing.Size)(this["logFileViewerSize"]));
            }
            set {
                this["logFileViewerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point logFileViewerLocation {
            get {
                return ((global::System.Drawing.Point)(this["logFileViewerLocation"]));
            }
            set {
                this["logFileViewerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BackupOldLogsAfterClearingAtMidnight {
            get {
                return ((bool)(this["BackupOldLogsAfterClearingAtMidnight"]));
            }
            set {
                this["BackupOldLogsAfterClearingAtMidnight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolCheckForUpdates {
            get {
                return ((bool)(this["boolCheckForUpdates"]));
            }
            set {
                this["boolCheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DateChooserWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["DateChooserWindowLocation"]));
            }
            set {
                this["DateChooserWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DateFormat {
            get {
                return ((byte)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDateFormat {
            get {
                return ((string)(this["CustomDateFormat"]));
            }
            set {
                this["CustomDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("816, 403")]
        public global::System.Drawing.Size ViewLogBackupsSize {
            get {
                return ((global::System.Drawing.Size)(this["ViewLogBackupsSize"]));
            }
            set {
                this["ViewLogBackupsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTCPServer {
            get {
                return ((bool)(this["EnableTCPServer"]));
            }
            set {
                this["EnableTCPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int RemoteProcessHeaderSize {
            get {
                return ((int)(this["RemoteProcessHeaderSize"]));
            }
            set {
                this["RemoteProcessHeaderSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int LogTypeWidth {
            get {
                return ((int)(this["LogTypeWidth"]));
            }
            set {
                this["LogTypeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int HostnameWidth {
            get {
                return ((int)(this["HostnameWidth"]));
            }
            set {
                this["HostnameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ServerTimeWidth {
            get {
                return ((int)(this["ServerTimeWidth"]));
            }
            set {
                this["ServerTimeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolShowHostnameColumn {
            get {
                return ((bool)(this["boolShowHostnameColumn"]));
            }
            set {
                this["boolShowHostnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolShowServerTimeColumn {
            get {
                return ((bool)(this["boolShowServerTimeColumn"]));
            }
            set {
                this["boolShowServerTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolShowLogTypeColumn {
            get {
                return ((bool)(this["boolShowLogTypeColumn"]));
            }
            set {
                this["boolShowLogTypeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveNumbersFromRemoteApp {
            get {
                return ((bool)(this["RemoveNumbersFromRemoteApp"]));
            }
            set {
                this["RemoveNumbersFromRemoteApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPv6Support {
            get {
                return ((bool)(this["IPv6Support"]));
            }
            set {
                this["IPv6Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool boolShowRawLogOnLogViewer {
            get {
                return ((bool)(this["boolShowRawLogOnLogViewer"]));
            }
            set {
                this["boolShowRawLogOnLogViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection hostnames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["hostnames"]));
            }
            set {
                this["hostnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolShowHiddenFilesOnViewLogBackyupsWindow {
            get {
                return ((bool)(this["boolShowHiddenFilesOnViewLogBackyupsWindow"]));
            }
            set {
                this["boolShowHiddenFilesOnViewLogBackyupsWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolShowHiddenAsGray {
            get {
                return ((bool)(this["boolShowHiddenAsGray"]));
            }
            set {
                this["boolShowHiddenAsGray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font font {
            get {
                return ((global::System.Drawing.Font)(this["font"]));
            }
            set {
                this["font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int ColViewLogBackupsFileSize {
            get {
                return ((int)(this["ColViewLogBackupsFileSize"]));
            }
            set {
                this["ColViewLogBackupsFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int ColViewLogBackupsFileDate {
            get {
                return ((int)(this["ColViewLogBackupsFileDate"]));
            }
            set {
                this["ColViewLogBackupsFileDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int ColViewLogBackupsFileName {
            get {
                return ((int)(this["ColViewLogBackupsFileName"]));
            }
            set {
                this["ColViewLogBackupsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeBetweenSameNotifications {
            get {
                return ((int)(this["TimeBetweenSameNotifications"]));
            }
            set {
                this["TimeBetweenSameNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeButtonsOnNotifications {
            get {
                return ((bool)(this["IncludeButtonsOnNotifications"]));
            }
            set {
                this["IncludeButtonsOnNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte NotificationLength {
            get {
                return ((byte)(this["NotificationLength"]));
            }
            set {
                this["NotificationLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("776, 426")]
        public global::System.Drawing.Size AlertHistorySize {
            get {
                return ((global::System.Drawing.Size)(this["AlertHistorySize"]));
            }
            set {
                this["AlertHistorySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AlertHistoryLocation {
            get {
                return ((global::System.Drawing.Point)(this["AlertHistoryLocation"]));
            }
            set {
                this["AlertHistoryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection logsColumnOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["logsColumnOrder"]));
            }
            set {
                this["logsColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection fileListColumnOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["fileListColumnOrder"]));
            }
            set {
                this["fileListColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection alertsHistoryColumnOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["alertsHistoryColumnOrder"]));
            }
            set {
                this["alertsHistoryColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point hostnamesLocation {
            get {
                return ((global::System.Drawing.Point)(this["hostnamesLocation"]));
            }
            set {
                this["hostnamesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point syslogProxyLocation {
            get {
                return ((global::System.Drawing.Point)(this["syslogProxyLocation"]));
            }
            set {
                this["syslogProxyLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int viewLogBackupsEntryCountColumnSize {
            get {
                return ((int)(this["viewLogBackupsEntryCountColumnSize"]));
            }
            set {
                this["viewLogBackupsEntryCountColumnSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool colLogAutoFill {
            get {
                return ((bool)(this["colLogAutoFill"]));
            }
            set {
                this["colLogAutoFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool disableAutoScrollUponScrolling {
            get {
                return ((bool)(this["disableAutoScrollUponScrolling"]));
            }
            set {
                this["disableAutoScrollUponScrolling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int viewLogBackupsHiddenColumnSize {
            get {
                return ((int)(this["viewLogBackupsHiddenColumnSize"]));
            }
            set {
                this["viewLogBackupsHiddenColumnSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int columnAlertedSize {
            get {
                return ((int)(this["columnAlertedSize"]));
            }
            set {
                this["columnAlertedSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int columnFileNameSize {
            get {
                return ((int)(this["columnFileNameSize"]));
            }
            set {
                this["columnFileNameSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolDebug {
            get {
                return ((bool)(this["boolDebug"]));
            }
            set {
                this["boolDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmDelete {
            get {
                return ((bool)(this["ConfirmDelete"]));
            }
            set {
                this["ConfirmDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreSearchResultLimits {
            get {
                return ((bool)(this["IgnoreSearchResultLimits"]));
            }
            set {
                this["IgnoreSearchResultLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFileDeletions {
            get {
                return ((bool)(this["LogFileDeletions"]));
            }
            set {
                this["LogFileDeletions"] = value;
            }
        }
    }
}
