'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.9.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property logFileLocation() As String
            Get
                Return CType(Me("logFileLocation"), String)
            End Get
            Set
                Me("logFileLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("816, 173")>
        Public Property logViewerWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("logViewerWindowSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("logViewerWindowSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property autoScroll() As Boolean
            Get
                Return CType(Me("autoScroll"), Boolean)
            End Get
            Set
                Me("autoScroll") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1191, 485")>
        Public Property mainWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("mainWindowSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("mainWindowSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("196")>
        Public Property columnTimeSize() As Integer
            Get
                Return CType(Me("columnTimeSize"), Integer)
            End Get
            Set
                Me("columnTimeSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("102")>
        Public Property columnIPSize() As Integer
            Get
                Return CType(Me("columnIPSize"), Integer)
            End Get
            Set
                Me("columnIPSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("670")>
        Public Property columnLogSize() As Integer
            Get
                Return CType(Me("columnLogSize"), Integer)
            End Get
            Set
                Me("columnLogSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property autoSave() As Boolean
            Get
                Return CType(Me("autoSave"), Boolean)
            End Get
            Set
                Me("autoSave") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("5")>
        Public Property autoSaveMinutes() As Short
            Get
                Return CType(Me("autoSaveMinutes"), Short)
            End Get
            Set
                Me("autoSaveMinutes") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("514")>
        Public Property sysLogPort() As Integer
            Get
                Return CType(Me("sysLogPort"), Integer)
            End Get
            Set
                Me("sysLogPort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property ignored() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ignored"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ignored") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("LightBlue")>
        Public Property searchColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("searchColor"), Global.System.Drawing.Color)
            End Get
            Set
                Me("searchColor") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1168, 464")>
        Public Property ignoredWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ignoredWindowSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ignoredWindowSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property windowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("windowLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("windowLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property ignoredWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("ignoredWindowLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("ignoredWindowLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property ignoredWordsLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("ignoredWordsLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("ignoredWordsLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property recordIgnoredLogs() As Boolean
            Get
                Return CType(Me("recordIgnoredLogs"), Boolean)
            End Get
            Set
                Me("recordIgnoredLogs") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property replacements() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("replacements"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("replacements") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property boolMaximized() As Boolean
            Get
                Return CType(Me("boolMaximized"), Boolean)
            End Get
            Set
                Me("boolMaximized") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolConfirmClose() As Boolean
            Get
                Return CType(Me("boolConfirmClose"), Boolean)
            End Get
            Set
                Me("boolConfirmClose") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property ignored2() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ignored2"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ignored2") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property replacementsLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("replacementsLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("replacementsLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property searchWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("searchWindowLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("searchWindowLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1168, 464")>
        Public Property searchWindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("searchWindowSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("searchWindowSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property alerts() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("alerts"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("alerts") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property alertsLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("alertsLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("alertsLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolDeselectItemsWhenMinimizing() As Boolean
            Get
                Return CType(Me("boolDeselectItemsWhenMinimizing"), Boolean)
            End Get
            Set
                Me("boolDeselectItemsWhenMinimizing") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolShowAlertedColumn() As Boolean
            Get
                Return CType(Me("boolShowAlertedColumn"), Boolean)
            End Get
            Set
                Me("boolShowAlertedColumn") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("345")>
        Public Property colIgnoredReplace() As Integer
            Get
                Return CType(Me("colIgnoredReplace"), Integer)
            End Get
            Set
                Me("colIgnoredReplace") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colIgnoredRegex() As Integer
            Get
                Return CType(Me("colIgnoredRegex"), Integer)
            End Get
            Set
                Me("colIgnoredRegex") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("91")>
        Public Property colIgnoredCaseSensitive() As Integer
            Get
                Return CType(Me("colIgnoredCaseSensitive"), Integer)
            End Get
            Set
                Me("colIgnoredCaseSensitive") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colIgnoredEnabled() As Integer
            Get
                Return CType(Me("colIgnoredEnabled"), Integer)
            End Get
            Set
                Me("colIgnoredEnabled") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("345")>
        Public Property colReplacementsReplace() As Integer
            Get
                Return CType(Me("colReplacementsReplace"), Integer)
            End Get
            Set
                Me("colReplacementsReplace") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("345")>
        Public Property colReplacementsReplaceWith() As Integer
            Get
                Return CType(Me("colReplacementsReplaceWith"), Integer)
            End Get
            Set
                Me("colReplacementsReplaceWith") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colReplacementsRegex() As Integer
            Get
                Return CType(Me("colReplacementsRegex"), Integer)
            End Get
            Set
                Me("colReplacementsRegex") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("91")>
        Public Property colReplacementsCaseSensitive() As Integer
            Get
                Return CType(Me("colReplacementsCaseSensitive"), Integer)
            End Get
            Set
                Me("colReplacementsCaseSensitive") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colReplacementsEnabled() As Integer
            Get
                Return CType(Me("colReplacementsEnabled"), Integer)
            End Get
            Set
                Me("colReplacementsEnabled") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("308")>
        Public Property colAlertsAlertLogText() As Integer
            Get
                Return CType(Me("colAlertsAlertLogText"), Integer)
            End Get
            Set
                Me("colAlertsAlertLogText") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("257")>
        Public Property colAlertsAlertText() As Integer
            Get
                Return CType(Me("colAlertsAlertText"), Integer)
            End Get
            Set
                Me("colAlertsAlertText") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colAlertsRegex() As Integer
            Get
                Return CType(Me("colAlertsRegex"), Integer)
            End Get
            Set
                Me("colAlertsRegex") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("91")>
        Public Property colAlertsCaseSensitive() As Integer
            Get
                Return CType(Me("colAlertsCaseSensitive"), Integer)
            End Get
            Set
                Me("colAlertsCaseSensitive") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("90")>
        Public Property colAlertsType() As Integer
            Get
                Return CType(Me("colAlertsType"), Integer)
            End Get
            Set
                Me("colAlertsType") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property colAlertsEnabled() As Integer
            Get
                Return CType(Me("colAlertsEnabled"), Integer)
            End Get
            Set
                Me("colAlertsEnabled") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("670, 304")>
        Public Property ConfigureIgnoredSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ConfigureIgnoredSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ConfigureIgnoredSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1051, 489")>
        Public Property ConfigureReplacementsSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ConfigureReplacementsSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ConfigureReplacementsSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1003, 322")>
        Public Property ConfigureAlertsSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ConfigureAlertsSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ConfigureAlertsSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property ServersToSendTo() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ServersToSendTo"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ServersToSendTo") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property MinimizeToClockTray() As Boolean
            Get
                Return CType(Me("MinimizeToClockTray"), Boolean)
            End Get
            Set
                Me("MinimizeToClockTray") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property DeleteOldLogsAtMidnight() As Boolean
            Get
                Return CType(Me("DeleteOldLogsAtMidnight"), Boolean)
            End Get
            Set
                Me("DeleteOldLogsAtMidnight") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1168, 464")>
        Public Property logFileViewerSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("logFileViewerSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("logFileViewerSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property logFileViewerLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("logFileViewerLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("logFileViewerLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property BackupOldLogsAfterClearingAtMidnight() As Boolean
            Get
                Return CType(Me("BackupOldLogsAfterClearingAtMidnight"), Boolean)
            End Get
            Set
                Me("BackupOldLogsAfterClearingAtMidnight") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolCheckForUpdates() As Boolean
            Get
                Return CType(Me("boolCheckForUpdates"), Boolean)
            End Get
            Set
                Me("boolCheckForUpdates") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property DateChooserWindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("DateChooserWindowLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("DateChooserWindowLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property DateFormat() As Byte
            Get
                Return CType(Me("DateFormat"), Byte)
            End Get
            Set
                Me("DateFormat") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CustomDateFormat() As String
            Get
                Return CType(Me("CustomDateFormat"), String)
            End Get
            Set
                Me("CustomDateFormat") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("816, 403")>
        Public Property ViewLogBackupsSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ViewLogBackupsSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ViewLogBackupsSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property EnableTCPServer() As Boolean
            Get
                Return CType(Me("EnableTCPServer"), Boolean)
            End Get
            Set
                Me("EnableTCPServer") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("150")>
        Public Property RemoteProcessHeaderSize() As Integer
            Get
                Return CType(Me("RemoteProcessHeaderSize"), Integer)
            End Get
            Set
                Me("RemoteProcessHeaderSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("200")>
        Public Property LogTypeWidth() As Integer
            Get
                Return CType(Me("LogTypeWidth"), Integer)
            End Get
            Set
                Me("LogTypeWidth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("150")>
        Public Property HostnameWidth() As Integer
            Get
                Return CType(Me("HostnameWidth"), Integer)
            End Get
            Set
                Me("HostnameWidth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("150")>
        Public Property ServerTimeWidth() As Integer
            Get
                Return CType(Me("ServerTimeWidth"), Integer)
            End Get
            Set
                Me("ServerTimeWidth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolShowHostnameColumn() As Boolean
            Get
                Return CType(Me("boolShowHostnameColumn"), Boolean)
            End Get
            Set
                Me("boolShowHostnameColumn") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolShowServerTimeColumn() As Boolean
            Get
                Return CType(Me("boolShowServerTimeColumn"), Boolean)
            End Get
            Set
                Me("boolShowServerTimeColumn") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolShowLogTypeColumn() As Boolean
            Get
                Return CType(Me("boolShowLogTypeColumn"), Boolean)
            End Get
            Set
                Me("boolShowLogTypeColumn") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property RemoveNumbersFromRemoteApp() As Boolean
            Get
                Return CType(Me("RemoveNumbersFromRemoteApp"), Boolean)
            End Get
            Set
                Me("RemoveNumbersFromRemoteApp") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property IPv6Support() As Boolean
            Get
                Return CType(Me("IPv6Support"), Boolean)
            End Get
            Set
                Me("IPv6Support") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property boolShowRawLogOnLogViewer() As Boolean
            Get
                Return CType(Me("boolShowRawLogOnLogViewer"), Boolean)
            End Get
            Set
                Me("boolShowRawLogOnLogViewer") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property hostnames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("hostnames"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("hostnames") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property boolShowHiddenFilesOnViewLogBackyupsWindow() As Boolean
            Get
                Return CType(Me("boolShowHiddenFilesOnViewLogBackyupsWindow"), Boolean)
            End Get
            Set
                Me("boolShowHiddenFilesOnViewLogBackyupsWindow") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property boolShowHiddenAsGray() As Boolean
            Get
                Return CType(Me("boolShowHiddenAsGray"), Boolean)
            End Get
            Set
                Me("boolShowHiddenAsGray") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")>
        Public Property font() As Global.System.Drawing.Font
            Get
                Return CType(Me("font"), Global.System.Drawing.Font)
            End Get
            Set
                Me("font") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("240")>
        Public Property ColViewLogBackupsFileSize() As Integer
            Get
                Return CType(Me("ColViewLogBackupsFileSize"), Integer)
            End Get
            Set
                Me("ColViewLogBackupsFileSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("240")>
        Public Property ColViewLogBackupsFileDate() As Integer
            Get
                Return CType(Me("ColViewLogBackupsFileDate"), Integer)
            End Get
            Set
                Me("ColViewLogBackupsFileDate") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("240")>
        Public Property ColViewLogBackupsFileName() As Integer
            Get
                Return CType(Me("ColViewLogBackupsFileName"), Integer)
            End Get
            Set
                Me("ColViewLogBackupsFileName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property TimeBetweenSameNotifications() As Integer
            Get
                Return CType(Me("TimeBetweenSameNotifications"), Integer)
            End Get
            Set
                Me("TimeBetweenSameNotifications") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property IncludeButtonsOnNotifications() As Boolean
            Get
                Return CType(Me("IncludeButtonsOnNotifications"), Boolean)
            End Get
            Set
                Me("IncludeButtonsOnNotifications") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property NotificationLength() As Byte
            Get
                Return CType(Me("NotificationLength"), Byte)
            End Get
            Set
                Me("NotificationLength") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("776, 426")>
        Public Property AlertHistorySize() As Global.System.Drawing.Size
            Get
                Return CType(Me("AlertHistorySize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("AlertHistorySize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property AlertHistoryLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("AlertHistoryLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("AlertHistoryLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property logsColumnOrder() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("logsColumnOrder"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("logsColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property fileListColumnOrder() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("fileListColumnOrder"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("fileListColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property alertsHistoryColumnOrder() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("alertsHistoryColumnOrder"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("alertsHistoryColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property hostnamesLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("hostnamesLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("hostnamesLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>
        Public Property syslogProxyLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("syslogProxyLocation"), Global.System.Drawing.Point)
            End Get
            Set
                Me("syslogProxyLocation") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("125")>
        Public Property viewLogBackupsEntryCountColumnSize() As Integer
            Get
                Return CType(Me("viewLogBackupsEntryCountColumnSize"), Integer)
            End Get
            Set
                Me("viewLogBackupsEntryCountColumnSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property colLogAutoFill() As Boolean
            Get
                Return CType(Me("colLogAutoFill"), Boolean)
            End Get
            Set
                Me("colLogAutoFill") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property disableAutoScrollUponScrolling() As Boolean
            Get
                Return CType(Me("disableAutoScrollUponScrolling"), Boolean)
            End Get
            Set
                Me("disableAutoScrollUponScrolling") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property viewLogBackupsHiddenColumnSize() As Integer
            Get
                Return CType(Me("viewLogBackupsHiddenColumnSize"), Integer)
            End Get
            Set
                Me("viewLogBackupsHiddenColumnSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("50")>
        Public Property columnAlertedSize() As Integer
            Get
                Return CType(Me("columnAlertedSize"), Integer)
            End Get
            Set
                Me("columnAlertedSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("150")>
        Public Property columnFileNameSize() As Integer
            Get
                Return CType(Me("columnFileNameSize"), Integer)
            End Get
            Set
                Me("columnFileNameSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property boolDebug() As Boolean
            Get
                Return CType(Me("boolDebug"), Boolean)
            End Get
            Set
                Me("boolDebug") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property ConfirmDelete() As Boolean
            Get
                Return CType(Me("ConfirmDelete"), Boolean)
            End Get
            Set
                Me("ConfirmDelete") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property IgnoreSearchResultLimits() As Boolean
            Get
                Return CType(Me("IgnoreSearchResultLimits"), Boolean)
            End Get
            Set
                Me("IgnoreSearchResultLimits") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property LogFileDeletions() As Boolean
            Get
                Return CType(Me("LogFileDeletions"), Boolean)
            End Get
            Set
                Me("LogFileDeletions") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ProcessReplacementsInSyslogDataFirst() As Boolean
            Get
                Return CType(Me("ProcessReplacementsInSyslogDataFirst"), Boolean)
            End Get
            Set
                Me("ProcessReplacementsInSyslogDataFirst") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>
        Public Property LimitNumberOfIgnoredLogs() As Integer
            Get
                Return CType(Me("LimitNumberOfIgnoredLogs"), Integer)
            End Get
            Set
                Me("LimitNumberOfIgnoredLogs") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AskOpenExplorer() As Boolean
            Get
                Return CType(Me("AskOpenExplorer"), Boolean)
            End Get
            Set
                Me("AskOpenExplorer") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property ignoredLogCount() As Long
            Get
                Return CType(Me("ignoredLogCount"), Long)
            End Get
            Set
                Me("ignoredLogCount") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property saveIgnoredLogCount() As Boolean
            Get
                Return CType(Me("saveIgnoredLogCount"), Boolean)
            End Get
            Set
                Me("saveIgnoredLogCount") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("180")>
        Public Property colIgnoredDateCreated() As Integer
            Get
                Return CType(Me("colIgnoredDateCreated"), Integer)
            End Get
            Set
                Me("colIgnoredDateCreated") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property ShowCloseButtonOnNotifications() As Boolean
            Get
                Return CType(Me("ShowCloseButtonOnNotifications"), Boolean)
            End Get
            Set
                Me("ShowCloseButtonOnNotifications") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"), Boolean)
            End Get
            Set
                Me("FirstRun") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property OnlySaveAlertedLogs() As Boolean
            Get
                Return CType(Me("OnlySaveAlertedLogs"), Boolean)
            End Get
            Set
                Me("OnlySaveAlertedLogs") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("240")>
        Public Property DateOfLastEventColumnWidth() As Integer
            Get
                Return CType(Me("DateOfLastEventColumnWidth"), Integer)
            End Get
            Set
                Me("DateOfLastEventColumnWidth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property IgnoredWordsAndPhrasesColumnOrder() As String
            Get
                Return CType(Me("IgnoredWordsAndPhrasesColumnOrder"), String)
            End Get
            Set
                Me("IgnoredWordsAndPhrasesColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property alertsColumnOrder() As String
            Get
                Return CType(Me("alertsColumnOrder"), String)
            End Get
            Set
                Me("alertsColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property replacementsColumnOrder() As String
            Get
                Return CType(Me("replacementsColumnOrder"), String)
            End Get
            Set
                Me("replacementsColumnOrder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("100")>
        Public Property ColSinceLastEventWidth() As Integer
            Get
                Return CType(Me("ColSinceLastEventWidth"), Integer)
            End Get
            Set
                Me("ColSinceLastEventWidth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AutomaticStatRefreshOnIgnoredWordsAndPhrases() As Boolean
            Get
                Return CType(Me("AutomaticStatRefreshOnIgnoredWordsAndPhrases"), Boolean)
            End Get
            Set
                Me("AutomaticStatRefreshOnIgnoredWordsAndPhrases") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AutomaticStatRefreshOnIfActiveOnIgnoredWordsAndPhrases() As Boolean
            Get
                Return CType(Me("AutomaticStatRefreshOnIfActiveOnIgnoredWordsAndPhrases"), Boolean)
            End Get
            Set
                Me("AutomaticStatRefreshOnIfActiveOnIgnoredWordsAndPhrases") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property IncludeCommasInDHMS() As Boolean
            Get
                Return CType(Me("IncludeCommasInDHMS"), Boolean)
            End Get
            Set
                Me("IncludeCommasInDHMS") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property ShowCompressionSizeDifference() As Boolean
            Get
                Return CType(Me("ShowCompressionSizeDifference"), Boolean)
            End Get
            Set
                Me("ShowCompressionSizeDifference") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property ShowCompressionSizeDifferencePercentage() As Boolean
            Get
                Return CType(Me("ShowCompressionSizeDifferencePercentage"), Boolean)
            End Get
            Set
                Me("ShowCompressionSizeDifferencePercentage") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property CompressBackupLogFiles() As Boolean
            Get
                Return CType(Me("CompressBackupLogFiles"), Boolean)
            End Get
            Set
                Me("CompressBackupLogFiles") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ClearIgnoredStatsAtMidnight() As Boolean
            Get
                Return CType(Me("ClearIgnoredStatsAtMidnight"), Boolean)
            End Get
            Set
                Me("ClearIgnoredStatsAtMidnight") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AlertsHistoryAlertColumnFill() As Boolean
            Get
                Return CType(Me("AlertsHistoryAlertColumnFill"), Boolean)
            End Get
            Set
                Me("AlertsHistoryAlertColumnFill") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("100")>
        Public Property AlertsHistoryFileNameColumnSize() As Integer
            Get
                Return CType(Me("AlertsHistoryFileNameColumnSize"), Integer)
            End Get
            Set
                Me("AlertsHistoryFileNameColumnSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ShowAlertsFromAllFiles() As Boolean
            Get
                Return CType(Me("ShowAlertsFromAllFiles"), Boolean)
            End Get
            Set
                Me("ShowAlertsFromAllFiles") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ShowAlertsFromAllFilesWithHiddenFiles() As Boolean
            Get
                Return CType(Me("ShowAlertsFromAllFilesWithHiddenFiles"), Boolean)
            End Get
            Set
                Me("ShowAlertsFromAllFilesWithHiddenFiles") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Public Property CustomColors() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("CustomColors"), Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("CustomColors") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("733, 326")>
        Public Property ColorPickerDialogSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("ColorPickerDialogSize"), Global.System.Drawing.Size)
            End Get
            Set
                Me("ColorPickerDialogSize") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ShowAsAlertedEvenIfLimitedByTime() As Boolean
            Get
                Return CType(Me("ShowAsAlertedEvenIfLimitedByTime"), Boolean)
            End Get
            Set
                Me("ShowAsAlertedEvenIfLimitedByTime") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Free_SysLog.My.MySettings
            Get
                Return Global.Free_SysLog.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
