// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;


namespace Free_SysLog.My
{

    [CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {

        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        */
        private static bool addedHandler;

        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (MyProject.Application.SaveMySettingsOnExit)
            {
                MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string logFileLocation
        {
            get
            {
                return Conversions.ToString(this["logFileLocation"]);
            }
            set
            {
                this["logFileLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("816, 173")]
        public Size logViewerWindowSize
        {
            get
            {
                return (Size)this["logViewerWindowSize"];
            }
            set
            {
                this["logViewerWindowSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool autoScroll
        {
            get
            {
                return Conversions.ToBoolean(this["autoScroll"]);
            }
            set
            {
                this["autoScroll"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1191, 485")]
        public Size mainWindowSize
        {
            get
            {
                return (Size)this["mainWindowSize"];
            }
            set
            {
                this["mainWindowSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("196")]
        public int columnTimeSize
        {
            get
            {
                return Conversions.ToInteger(this["columnTimeSize"]);
            }
            set
            {
                this["columnTimeSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("102")]
        public int columnIPSize
        {
            get
            {
                return Conversions.ToInteger(this["columnIPSize"]);
            }
            set
            {
                this["columnIPSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("670")]
        public int columnLogSize
        {
            get
            {
                return Conversions.ToInteger(this["columnLogSize"]);
            }
            set
            {
                this["columnLogSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool autoSave
        {
            get
            {
                return Conversions.ToBoolean(this["autoSave"]);
            }
            set
            {
                this["autoSave"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("5")]
        public short autoSaveMinutes
        {
            get
            {
                return Conversions.ToShort(this["autoSaveMinutes"]);
            }
            set
            {
                this["autoSaveMinutes"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("514")]
        public int sysLogPort
        {
            get
            {
                return Conversions.ToInteger(this["sysLogPort"]);
            }
            set
            {
                this["sysLogPort"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection ignored
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["ignored"];
            }
            set
            {
                this["ignored"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("LightBlue")]
        public Color searchColor
        {
            get
            {
                return (Color)this["searchColor"];
            }
            set
            {
                this["searchColor"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1168, 464")]
        public Size ignoredWindowSize
        {
            get
            {
                return (Size)this["ignoredWindowSize"];
            }
            set
            {
                this["ignoredWindowSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point windowLocation
        {
            get
            {
                return (Point)this["windowLocation"];
            }
            set
            {
                this["windowLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point ignoredWindowLocation
        {
            get
            {
                return (Point)this["ignoredWindowLocation"];
            }
            set
            {
                this["ignoredWindowLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point ignoredWordsLocation
        {
            get
            {
                return (Point)this["ignoredWordsLocation"];
            }
            set
            {
                this["ignoredWordsLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool recordIgnoredLogs
        {
            get
            {
                return Conversions.ToBoolean(this["recordIgnoredLogs"]);
            }
            set
            {
                this["recordIgnoredLogs"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection replacements
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["replacements"];
            }
            set
            {
                this["replacements"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool boolMaximized
        {
            get
            {
                return Conversions.ToBoolean(this["boolMaximized"]);
            }
            set
            {
                this["boolMaximized"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolConfirmClose
        {
            get
            {
                return Conversions.ToBoolean(this["boolConfirmClose"]);
            }
            set
            {
                this["boolConfirmClose"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection ignored2
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["ignored2"];
            }
            set
            {
                this["ignored2"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point replacementsLocation
        {
            get
            {
                return (Point)this["replacementsLocation"];
            }
            set
            {
                this["replacementsLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point searchWindowLocation
        {
            get
            {
                return (Point)this["searchWindowLocation"];
            }
            set
            {
                this["searchWindowLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1168, 464")]
        public Size searchWindowSize
        {
            get
            {
                return (Size)this["searchWindowSize"];
            }
            set
            {
                this["searchWindowSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection alerts
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["alerts"];
            }
            set
            {
                this["alerts"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point alertsLocation
        {
            get
            {
                return (Point)this["alertsLocation"];
            }
            set
            {
                this["alertsLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolDeselectItemsWhenMinimizing
        {
            get
            {
                return Conversions.ToBoolean(this["boolDeselectItemsWhenMinimizing"]);
            }
            set
            {
                this["boolDeselectItemsWhenMinimizing"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolShowAlertedColumn
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowAlertedColumn"]);
            }
            set
            {
                this["boolShowAlertedColumn"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("345")]
        public int colIgnoredReplace
        {
            get
            {
                return Conversions.ToInteger(this["colIgnoredReplace"]);
            }
            set
            {
                this["colIgnoredReplace"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colIgnoredRegex
        {
            get
            {
                return Conversions.ToInteger(this["colIgnoredRegex"]);
            }
            set
            {
                this["colIgnoredRegex"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("91")]
        public int colIgnoredCaseSensitive
        {
            get
            {
                return Conversions.ToInteger(this["colIgnoredCaseSensitive"]);
            }
            set
            {
                this["colIgnoredCaseSensitive"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colIgnoredEnabled
        {
            get
            {
                return Conversions.ToInteger(this["colIgnoredEnabled"]);
            }
            set
            {
                this["colIgnoredEnabled"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("345")]
        public int colReplacementsReplace
        {
            get
            {
                return Conversions.ToInteger(this["colReplacementsReplace"]);
            }
            set
            {
                this["colReplacementsReplace"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("345")]
        public int colReplacementsReplaceWith
        {
            get
            {
                return Conversions.ToInteger(this["colReplacementsReplaceWith"]);
            }
            set
            {
                this["colReplacementsReplaceWith"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colReplacementsRegex
        {
            get
            {
                return Conversions.ToInteger(this["colReplacementsRegex"]);
            }
            set
            {
                this["colReplacementsRegex"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("91")]
        public int colReplacementsCaseSensitive
        {
            get
            {
                return Conversions.ToInteger(this["colReplacementsCaseSensitive"]);
            }
            set
            {
                this["colReplacementsCaseSensitive"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colReplacementsEnabled
        {
            get
            {
                return Conversions.ToInteger(this["colReplacementsEnabled"]);
            }
            set
            {
                this["colReplacementsEnabled"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("308")]
        public int colAlertsAlertLogText
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsAlertLogText"]);
            }
            set
            {
                this["colAlertsAlertLogText"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("257")]
        public int colAlertsAlertText
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsAlertText"]);
            }
            set
            {
                this["colAlertsAlertText"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colAlertsRegex
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsRegex"]);
            }
            set
            {
                this["colAlertsRegex"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("91")]
        public int colAlertsCaseSensitive
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsCaseSensitive"]);
            }
            set
            {
                this["colAlertsCaseSensitive"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("90")]
        public int colAlertsType
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsType"]);
            }
            set
            {
                this["colAlertsType"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int colAlertsEnabled
        {
            get
            {
                return Conversions.ToInteger(this["colAlertsEnabled"]);
            }
            set
            {
                this["colAlertsEnabled"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("670, 304")]
        public Size ConfigureIgnoredSize
        {
            get
            {
                return (Size)this["ConfigureIgnoredSize"];
            }
            set
            {
                this["ConfigureIgnoredSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1051, 489")]
        public Size ConfigureReplacementsSize
        {
            get
            {
                return (Size)this["ConfigureReplacementsSize"];
            }
            set
            {
                this["ConfigureReplacementsSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1003, 322")]
        public Size ConfigureAlertsSize
        {
            get
            {
                return (Size)this["ConfigureAlertsSize"];
            }
            set
            {
                this["ConfigureAlertsSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection ServersToSendTo
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["ServersToSendTo"];
            }
            set
            {
                this["ServersToSendTo"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool MinimizeToClockTray
        {
            get
            {
                return Conversions.ToBoolean(this["MinimizeToClockTray"]);
            }
            set
            {
                this["MinimizeToClockTray"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool DeleteOldLogsAtMidnight
        {
            get
            {
                return Conversions.ToBoolean(this["DeleteOldLogsAtMidnight"]);
            }
            set
            {
                this["DeleteOldLogsAtMidnight"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1168, 464")]
        public Size logFileViewerSize
        {
            get
            {
                return (Size)this["logFileViewerSize"];
            }
            set
            {
                this["logFileViewerSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point logFileViewerLocation
        {
            get
            {
                return (Point)this["logFileViewerLocation"];
            }
            set
            {
                this["logFileViewerLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool BackupOldLogsAfterClearingAtMidnight
        {
            get
            {
                return Conversions.ToBoolean(this["BackupOldLogsAfterClearingAtMidnight"]);
            }
            set
            {
                this["BackupOldLogsAfterClearingAtMidnight"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolCheckForUpdates
        {
            get
            {
                return Conversions.ToBoolean(this["boolCheckForUpdates"]);
            }
            set
            {
                this["boolCheckForUpdates"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point DateChooserWindowLocation
        {
            get
            {
                return (Point)this["DateChooserWindowLocation"];
            }
            set
            {
                this["DateChooserWindowLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public byte DateFormat
        {
            get
            {
                return Conversions.ToByte(this["DateFormat"]);
            }
            set
            {
                this["DateFormat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string CustomDateFormat
        {
            get
            {
                return Conversions.ToString(this["CustomDateFormat"]);
            }
            set
            {
                this["CustomDateFormat"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("816, 403")]
        public Size ViewLogBackupsSize
        {
            get
            {
                return (Size)this["ViewLogBackupsSize"];
            }
            set
            {
                this["ViewLogBackupsSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool EnableTCPServer
        {
            get
            {
                return Conversions.ToBoolean(this["EnableTCPServer"]);
            }
            set
            {
                this["EnableTCPServer"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("150")]
        public int RemoteProcessHeaderSize
        {
            get
            {
                return Conversions.ToInteger(this["RemoteProcessHeaderSize"]);
            }
            set
            {
                this["RemoteProcessHeaderSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("200")]
        public int LogTypeWidth
        {
            get
            {
                return Conversions.ToInteger(this["LogTypeWidth"]);
            }
            set
            {
                this["LogTypeWidth"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("150")]
        public int HostnameWidth
        {
            get
            {
                return Conversions.ToInteger(this["HostnameWidth"]);
            }
            set
            {
                this["HostnameWidth"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("150")]
        public int ServerTimeWidth
        {
            get
            {
                return Conversions.ToInteger(this["ServerTimeWidth"]);
            }
            set
            {
                this["ServerTimeWidth"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolShowHostnameColumn
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowHostnameColumn"]);
            }
            set
            {
                this["boolShowHostnameColumn"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolShowServerTimeColumn
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowServerTimeColumn"]);
            }
            set
            {
                this["boolShowServerTimeColumn"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolShowLogTypeColumn
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowLogTypeColumn"]);
            }
            set
            {
                this["boolShowLogTypeColumn"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool RemoveNumbersFromRemoteApp
        {
            get
            {
                return Conversions.ToBoolean(this["RemoveNumbersFromRemoteApp"]);
            }
            set
            {
                this["RemoveNumbersFromRemoteApp"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool IPv6Support
        {
            get
            {
                return Conversions.ToBoolean(this["IPv6Support"]);
            }
            set
            {
                this["IPv6Support"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool boolShowRawLogOnLogViewer
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowRawLogOnLogViewer"]);
            }
            set
            {
                this["boolShowRawLogOnLogViewer"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection hostnames
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["hostnames"];
            }
            set
            {
                this["hostnames"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool boolShowHiddenFilesOnViewLogBackyupsWindow
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowHiddenFilesOnViewLogBackyupsWindow"]);
            }
            set
            {
                this["boolShowHiddenFilesOnViewLogBackyupsWindow"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool boolShowHiddenAsGray
        {
            get
            {
                return Conversions.ToBoolean(this["boolShowHiddenAsGray"]);
            }
            set
            {
                this["boolShowHiddenAsGray"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Microsoft Sans Serif, 8.25pt")]
        public Font font
        {
            get
            {
                return (Font)this["font"];
            }
            set
            {
                this["font"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("240")]
        public int ColViewLogBackupsFileSize
        {
            get
            {
                return Conversions.ToInteger(this["ColViewLogBackupsFileSize"]);
            }
            set
            {
                this["ColViewLogBackupsFileSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("240")]
        public int ColViewLogBackupsFileDate
        {
            get
            {
                return Conversions.ToInteger(this["ColViewLogBackupsFileDate"]);
            }
            set
            {
                this["ColViewLogBackupsFileDate"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("240")]
        public int ColViewLogBackupsFileName
        {
            get
            {
                return Conversions.ToInteger(this["ColViewLogBackupsFileName"]);
            }
            set
            {
                this["ColViewLogBackupsFileName"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int TimeBetweenSameNotifications
        {
            get
            {
                return Conversions.ToInteger(this["TimeBetweenSameNotifications"]);
            }
            set
            {
                this["TimeBetweenSameNotifications"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool IncludeButtonsOnNotifications
        {
            get
            {
                return Conversions.ToBoolean(this["IncludeButtonsOnNotifications"]);
            }
            set
            {
                this["IncludeButtonsOnNotifications"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public byte NotificationLength
        {
            get
            {
                return Conversions.ToByte(this["NotificationLength"]);
            }
            set
            {
                this["NotificationLength"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("776, 426")]
        public Size AlertHistorySize
        {
            get
            {
                return (Size)this["AlertHistorySize"];
            }
            set
            {
                this["AlertHistorySize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point AlertHistoryLocation
        {
            get
            {
                return (Point)this["AlertHistoryLocation"];
            }
            set
            {
                this["AlertHistoryLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection logsColumnOrder
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["logsColumnOrder"];
            }
            set
            {
                this["logsColumnOrder"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection fileListColumnOrder
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["fileListColumnOrder"];
            }
            set
            {
                this["fileListColumnOrder"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        public System.Collections.Specialized.StringCollection alertsHistoryColumnOrder
        {
            get
            {
                return (System.Collections.Specialized.StringCollection)this["alertsHistoryColumnOrder"];
            }
            set
            {
                this["alertsHistoryColumnOrder"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point hostnamesLocation
        {
            get
            {
                return (Point)this["hostnamesLocation"];
            }
            set
            {
                this["hostnamesLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0, 0")]
        public Point syslogProxyLocation
        {
            get
            {
                return (Point)this["syslogProxyLocation"];
            }
            set
            {
                this["syslogProxyLocation"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("125")]
        public int viewLogBackupsEntryCountColumnSize
        {
            get
            {
                return Conversions.ToInteger(this["viewLogBackupsEntryCountColumnSize"]);
            }
            set
            {
                this["viewLogBackupsEntryCountColumnSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool colLogAutoFill
        {
            get
            {
                return Conversions.ToBoolean(this["colLogAutoFill"]);
            }
            set
            {
                this["colLogAutoFill"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool disableAutoScrollUponScrolling
        {
            get
            {
                return Conversions.ToBoolean(this["disableAutoScrollUponScrolling"]);
            }
            set
            {
                this["disableAutoScrollUponScrolling"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("60")]
        public int viewLogBackupsHiddenColumnSize
        {
            get
            {
                return Conversions.ToInteger(this["viewLogBackupsHiddenColumnSize"]);
            }
            set
            {
                this["viewLogBackupsHiddenColumnSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("50")]
        public int columnAlertedSize
        {
            get
            {
                return Conversions.ToInteger(this["columnAlertedSize"]);
            }
            set
            {
                this["columnAlertedSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("150")]
        public int columnFileNameSize
        {
            get
            {
                return Conversions.ToInteger(this["columnFileNameSize"]);
            }
            set
            {
                this["columnFileNameSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool boolDebug
        {
            get
            {
                return Conversions.ToBoolean(this["boolDebug"]);
            }
            set
            {
                this["boolDebug"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool ConfirmDelete
        {
            get
            {
                return Conversions.ToBoolean(this["ConfirmDelete"]);
            }
            set
            {
                this["ConfirmDelete"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool IgnoreSearchResultLimits
        {
            get
            {
                return Conversions.ToBoolean(this["IgnoreSearchResultLimits"]);
            }
            set
            {
                this["IgnoreSearchResultLimits"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool LogFileDeletions
        {
            get
            {
                return Conversions.ToBoolean(this["LogFileDeletions"]);
            }
            set
            {
                this["LogFileDeletions"] = value;
            }
        }
    }
}

namespace Free_SysLog.My
{

    [HideModuleName()]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal static class MySettingsProperty
    {

        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}